earth-mover/icechunk

- README.md
This will help our page on PyPI (and Crates?) find the logo asset.
> Use absolute URL for logo in readme

- .codespellrc
- .github/workflows/codespell.yml
- .pre-commit-config.yaml
- README.md
- docs/docs/contributing.md
- docs/docs/faq.md
- docs/docs/icechunk-python/version-control.md
- docs/docs/icechunk-python/virtual.md
- docs/docs/overview.md
- docs/docs/spec.md
- icechunk-python/notebooks/demo-dummy-data.ipynb
- icechunk-python/notebooks/demo-s3.ipynb
- icechunk-python/python/icechunk/__init__.py
- icechunk-python/src/errors.rs
- icechunk-python/tests/test_zarr/test_api.py
- icechunk/examples/low_level_dataset.rs
- icechunk/src/lib.rs
- icechunk/src/refs.rs
- icechunk/src/repository.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/zarr.rs
- icechunk/tests/test_s3_storage.rs
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
TODOs:
> Add codespell support (config, workflow to detect/not fix) and make it fix few typos

- docs/docs/icechunk-python/xarray.md
> [Docs] correct module calls to match imports

- docs/docs/icechunk-python/xarray.md
> [Docs] correct output dimensions in xr example

- docs/docs/icechunk-python/configuration.md
- docs/docs/icechunk-python/virtual.md
- icechunk-python/python/icechunk/_icechunk_python.pyi
> [Docs] Improve virtual ref docs

- icechunk/src/zarr.rs
This new method works like `list_dir` but the returned stream has item `ListDirItem` which separates the keys from the prefixes.
Closes: https://github.com/earth-mover/icechunk/issues/276
> Introduce `Store::list_dir_items`

- .github/workflows/python-ci.yaml
* Removes pypi token to force using openid connect
* Triggers release only on wrokflow dispatch now
> Update python ci

- README.md
- docs/docs/spec.md
I had to commit with `--no-verify` since pre-commit was failing , filed a dedicated
- https://github.com/earth-mover/icechunk/issues/299
which I don't think relates to my changes, so hopefully they are lint-free ;)
> README minor tune up: syntax and other very minor typos etc

- icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py
- icechunk/src/zarr.rs
I believe `"attributes": null` in array/group metadata is not conformant to the Zarr V3 specification. If empty, it must be omitted entirely or be `"attributes": {}`.
https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#attributes
> The following members are optional:
>
> `attributes`
> The value must be an object. The object may contain any key/value pairs, where the key must be a string and the value can be an arbitrary JSON literal. Intended to allow storage of arbitrary user metadata.
> Fix non-conformant "attributes" metadata

- icechunk/src/repository.rs
- icechunk/src/zarr.rs
Closes #235
```
ValueError: store error: unsuccessful repository operation: `snapshot not found: `F000BARSPAM123456780``
```
> Error when checking out invalid snapshot ID

- icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py
Closes #348
not sure what to fix yet.
> Fix pickling of stores

- Cargo.lock
- icechunk/Cargo.toml
- icechunk/src/lib.rs
- icechunk/src/ops/gc.rs
- icechunk/src/ops/mod.rs
- icechunk/src/refs.rs
- icechunk/src/repository.rs
- icechunk/src/storage/caching.rs
- icechunk/src/storage/logging.rs
- icechunk/src/storage/mod.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
- icechunk/tests/test_gc.rs
We call garbage collection to the process where dangling objects are
deleted from object store.
We define a dangling object as a chunk, manifest, snapshot, attributes
or transaction log file that cannot be reached by navigating the
parent relationship starting from all possible refs.
There are currently two mechanisms that create dangling objects:
- Abandoning a session without committing it
- Resetting a branch leaving snapshots behind
In the future, we'll introduce more mechanisms that "generate" garbage,
with the objective of reducing storage costs. One example, would be
squashing commits when version resolution is not relevant.
Garbage collection is an inherently dangerous process. It's the only
time at which Icechunk actually deletes data from object store. As such,
it must be …
> Rust Icechunk learns how to collect garbage

- icechunk/src/storage/s3.rs
> Delete extra constants

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/storage.rs
I'm starting to read through the storage binding for #266.
As it stands, you recreate the content of the struct in the Python binding as well, and then you convert the _content_ of the struct in the Python bindings to the _content_ of the struct in the Rust code.
In my opinion it's best to have as little logic as possible in the binding code and make it a slim wrapper around the underlying core Rust code. Minimizing the logic in the bindings also makes it simpler to make bindings to other languages in the future (https://github.com/earth-mover/icechunk/issues/356)
> Simplify Python binding of `StorageConfig`

- docs/docs/contributing.md
Split between pre and post 1.0 roadmaps.
> Update roadmap documentation

- icechunk-python/python/icechunk/__init__.py
- icechunk-python/tests/test_pickle.py
> Set store to read only after unpickling

- icechunk-python/pyproject.toml
maturin 1.77 changed the error behavior and thats why the sdist error popped up this weekend
> Fix sdist readme packaging error

- icechunk/src/change_set.rs
- icechunk/src/zarr.rs
Closes #347
This bug manifests when groups or arrays were committed, and then are being overwritten. Zarr will delete the existing nodes first and then add them. This means the same node is in both the `new_*` and `deleted_*` hashmaps, and so getting the node fails (it prioritizes `deleted_groups` and returns KeyError)
> Allow overwriting existing groups and arrays

- icechunk-python/tests/test_store.py
- icechunk/src/change_set.rs
- icechunk/src/conflicts/basic_solver.rs
- icechunk/src/conflicts/detector.rs
- icechunk/src/conflicts/mod.rs
- icechunk/src/repository.rs
- icechunk/src/zarr.rs
Now track both Path and NodeId rather than just Path. This helps us handle tricky cases where a committed node is updated, deleted, and created again in the same session.
> Better deletion tracking in ChangeSet

- design-docs/001-virtual-chunk-improvements.md
These are early thoughts, feel free to provide feedback and different ideas. Also, particularly important: am I missing requirements?
Closes: #430
> Virtual chunks design document

- design-docs/002-rebase-commit-improvements.md
This document is mostly straightforward, but the biggest question is what do we do when a rebase fails within a session context? 
[#408](https://github.com/earth-mover/icechunk/issues/408)
> Add design doc for rebase and commit python api improvements

- icechunk-python/tests/test_stateful_repo_ops.py
xref #445 
This ports `test_stateful_repo_ops.py` from Arraylake to Icechunk. It's really nice how many special cases I could delete!
This needs some upstream pushes to Zarr, so I'll leave it in draft for a while. It passes locally.
> Add stateful testing for version control ops

- icechunk/proptest-regressions/storage/mod.txt
- icechunk/src/asset_manager.rs
- icechunk/src/session.rs
- icechunk/src/storage/logging.rs
- icechunk/src/storage/mod.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
- icechunk/src/virtual_chunks.rs
- icechunk/tests/test_storage.rs
Only applies if the chunk is large enough. Same logic as with manifests.
This still doesn't apply to virtual chunks, only native. For no reason, we can follow up with virtual chunks in a different PR.
This commit also fixes a bug in chunks with offset != 0 (wich cannot be constructed in IC today)
> Fetch chunks using concurrent requests

- icechunk-python/tests/test_stateful_repo_ops.py
- icechunk/src/repository.rs
Main branch is used to detect repository existence, so it shouldn't be deleted. It is also the default in several functions.
Closes: #515
> Disallow deleting main branch

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/store.py
- icechunk-python/src/store.rs
- icechunk-python/tests/test_virtual_ref.py
- icechunk/src/session.rs
- icechunk/src/store.rs
- icechunk/src/virtual_chunks.rs
- icechunk/tests/test_virtual_refs.rs
This argument, defaulted to `False` will make sure the location passed matches one of the existing virtual chunk containers.
Closes: #510
> Add `validate_container` argument to set_virtual_ref

- icechunk-python/src/repository.rs
- icechunk/src/repository.rs
This opens a new repository with the same "info" as the current one, optionally overriding config and virtual credentials.
> Add helper `Repository.reopen`

- icechunk/src/asset_manager.rs
- icechunk/src/storage/logging.rs
- icechunk/src/storage/mod.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
- icechunk/tests/test_storage.rs
This also reduces the duplication between object_store and S3 implementations of Storage.
> Concurrently download bytes

- icechunk/src/asset_manager.rs
- icechunk/src/format/manifest.rs
- icechunk/src/format/mod.rs
- icechunk/src/format/serializers/current.rs
- icechunk/src/format/serializers/mod.rs
- icechunk/src/format/snapshot.rs
- icechunk/src/format/transaction_log.rs
- icechunk/src/session.rs
Also provides a mechanism do separate the serializable datastructure from the in memory one.
To understand the mechanism read the documentation at the top of `serializers/mod.rs`.
After this merges, I'll try to use the mechanism to implement the first backwards-compatible on-disk format change.
> Mechanism to deserialize different spec versions

- icechunk-python/python/icechunk/__init__.py
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/storage.py
- icechunk-python/src/config.rs
- icechunk-python/tests/data/test-repo/config.yaml
- icechunk/src/config.rs
- icechunk/src/storage/mod.rs
- icechunk/src/virtual_chunks.rs
Tigris can now be used for Icechunk repositories and for virtual chunk containers.
Warning: Currently, if using Tigris for the repo storage, there are two behaviors that are broken:
* When creating a repository an assertions can sometimes trigger if the request is done from a region geographically far from where the data is. The repository is created successfully.
* There will be a delay between when commit is done and when it's visible in a branch. This breaks our consistency guarantees.
We are exploring ways to deal with the issues above.
> Experimental support for Tigris

- design-docs/007-basic-expiration.md
- icechunk-python/src/repository.rs
- icechunk/src/asset_manager.rs
- icechunk/src/format/snapshot.rs
- icechunk/src/ops/gc.rs
- icechunk/src/refs.rs
- icechunk/src/repository.rs
- icechunk/src/session.rs
- icechunk/tests/test_gc.rs
Also fix a bug where we were listing deleted tags.
Some minimal refactoring too.
> Implement expiration of snapshots

- docs/docs/icechunk-python/quickstart.md
Fixes a few small typos and missing imports that I ran into when trying out the quickstart. This should now run without any extra effort beyond copy pasting.
> Docs: fix errors in quickstart

- icechunk-python/tests/test_zarr/test_properties.py
- icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py
Zarr 3.0.3 included the ShardingCodec in hypothesis strategies
We don't seem to work with it.
> Skip sharding codec in test

- icechunk-python/benchmarks/conftest.py
- icechunk-python/benchmarks/helpers.py
- icechunk-python/benchmarks/most_recent.sh
- icechunk-python/benchmarks/runner.py
@paraseba 
```
python benchmarks/runner.py --pytest="-k open" --where s3 main
```
works for me. It will *print* results to screen for now. The pytest kwarg simply runs a set of short test. Delete to run the whole thing
> Remote benchmark tweaks

- icechunk-python/benchmarks/test_benchmark_reads.py
Zarr doesn't support a preceding slash either, so I think icechunk was mistakenly supporting it.
```python
import zarr
store = zarr.storage.MemoryStore()
group = zarr.group(store)
array = group.create_array("array", shape=(1,2,3), dtype="float32")
print(await store.getsize("array/zarr.json")) # works
await store.getsize("/array/zarr.json") #error
```
> Fix getsize benchmark

- Cargo.toml
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/config.rs
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_config.py
- icechunk/examples/multithreaded_store.rs
- icechunk/src/storage/mod.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
- icechunk/tests/test_storage.rs
- icechunk/tests/test_virtual_refs.rs
> Add optional overrides for nonconforming object stores

- Changelog.python.md
- docs/docs/icechunk-python/quickstart.md
- docs/docs/icechunk-python/xarray.md
- icechunk-python/notebooks/demo-dummy-data.ipynb
- icechunk-python/notebooks/version-control.ipynb
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_can_read_old.py
- icechunk-python/tests/test_stateful_repo_ops.py
- icechunk-python/tests/test_timetravel.py
Aligning the parameter names: always using `snapshot_id` for the string id
Closes https://github.com/earth-mover/icechunk/issues/676
Made the changes in
- `ancestry`
- `async_ancestry`
- `diff`
- `readonly_session`
There are a few more errors that could be changed ([1](https://github.com/DahnJ/icechunk/blob/feat/dj-unify-session-id/icechunk/src/refs.rs#L120), [2](https://github.com/DahnJ/icechunk/blob/feat/dj-unify-session-id/icechunk/src/session.rs#L96)) and some internal uses ([example](https://github.com/DahnJ/icechunk/blob/feat/dj-unify-session-id/icechunk/src/storage/logging.rs#L207)) that I didn't change. Let me know if they should also be aligned.
> feat: unify API on snapshot_id

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_timetravel.py
- icechunk/src/repository.rs
This can be easily extended to other methods, such as `ancestry` and `diff`.
Closes: #382
> `readonly_session("main", as_of=...)` to open a branch at a timestamp

- icechunk-python/python/icechunk/repository.py
- icechunk-python/python/icechunk/store.py
Caught these when using `--strict` in the docs build in preparation for executable docs
> doc: fix wrong name in docstrings

- icechunk/src/repository.rs
- icechunk/src/storage/logging.rs
- icechunk/src/storage/mod.rs
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
Why:
* We may implement `Storage` for certain read-only s3-like, such as HTTP
* We'll need this for [Tigris support](https://github.com/earth-mover/icechunk/blob/main/design-docs/009-tigris-support.md)
> Support for read-only Storage

- icechunk-python/src/lib.rs
Fix for #816 
Using Clap's [use_stderr](https://docs.rs/clap/latest/clap/type.Error.html#method.use_stderr) and [exit_code](https://docs.rs/clap/latest/clap/type.Error.html#method.exit_code) to correctly propagate error + exit code.
Also drops the `Error` printout as it's duplicating the information, the Rust implementation should report errors correctly by itself.
> fix(lib.rs): Python CLI issues 0 exit code when using --help

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_stats.py
- icechunk-python/tests/test_xarray.py
- icechunk/src/ops/gc.rs
- icechunk/src/ops/mod.rs
- icechunk/src/ops/stats.rs
- icechunk/tests/test_stats.rs
This new method in the `Repository` class computes the total space used by chunks in all snapshots. Only native, pointed chunks are included.
Closes: #836
> New `total_chunks_storage` function

- icechunk/src/storage/object_store.rs
Some leftover code was doing unconditional multipart uploads of chunks, in the object store that use `object_store` (gcs, local, etc).
This was producing for usual chunk sizes ~ 3x performance penalty.
We should add multipart back, but only for large objects.
Closes: #723
> Don't do multipart uploads for chunks

- icechunk-python/python/icechunk/session.py
I noticed as I was looking through the docs that the `metadata` param in `commit()` isn't documented
> doc: update docstring to include metadata param

- icechunk/src/ops/gc.rs
- icechunk/tests/test_gc.rs
This happens if `older_than` < root.flushed_at.
The new test fails in the previous code.
> Fix bug in expiration that creates a commit loop

- icechunk-python/tests/test_stateful_repo_ops.py
Closes #867 
Adds both `expire_snapshots` and `garbage_collect`.
`expire_snapshots` is basically an independent reimplementation of the rust logic.
`garbage_collect` is very simple, and only deletes expires snapshots.
> Add expiration to stateful test

- .github/workflows/rust-ci.yaml
- Justfile
- icechunk/tests/common/mod.rs
- icechunk/tests/test_concurrency.rs
- icechunk/tests/test_distributed_writes.rs
- icechunk/tests/test_gc.rs
- icechunk/tests/test_stats.rs
- icechunk/tests/test_storage.rs
- icechunk/tests/test_virtual_refs.rs
We add a set of `ignored` tests that contact the real object stores: S3, R2, Tigris. These tests are the same Rust integration tests we were previously running against in memory or minio storages only.
To enable these tests, run `cargo test --ignored` with the following environment variables set:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_BUCKET
- AWS_REGION
- R2_ACCESS_KEY_ID
- R2_SECRET_ACCESS_KEY
- R2_BUCKET
- R2_ACCOUNT_ID
- TIGRIS_ACCESS_KEY_ID
- TIGRIS_SECRET_ACCESS_KEY
- TIGRIS_BUCKET
- TIGRIS_REGION
> Rust integration tests can run in more object stores.

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk/src/format/serializers/mod.rs
- icechunk/src/store.rs
- icechunk/src/virtual_chunks.rs
This looks like it was never updated when we treated zarr metadata as blobs
> Fix `Diff` python typing

- icechunk-python/tests/data/test-repo/config.yaml
- icechunk-python/tests/test_can_read_old.py
small refactor of test_can_read_old.py
> Add chunk container repr, fix test dataset

- Cargo.toml
- icechunk-python/Cargo.toml
- icechunk/src/storage/object_store.rs
- icechunk/src/storage/s3.rs
- icechunk/src/store.rs
I used
```
samply record -- python script.py
```
I also grepped for `write_`
```
-> % grep -B 2 "fn write_" icechunk/src/**/**.rs
icechunk/src/asset_manager.rs-
icechunk/src/asset_manager.rs-    #[instrument(skip(self, manifest))]
icechunk/src/asset_manager.rs:    pub async fn write_manifest(&self, manifest: Arc<Manifest>) -> RepositoryResult<u64> {
--
icechunk/src/asset_manager.rs-
icechunk/src/asset_manager.rs-    #[instrument(skip(self, snapshot))]
icechunk/src/asset_manager.rs:    pub async fn write_snapshot(&self, snapshot: Arc<Snapshot>) -> RepositoryResult<()> {
--
icechunk/src/asset_manager.rs-
icechunk/src/asset_manager.rs-    #[instrument(skip(self, log))]
icechunk/src/asset_manager.rs:    pub async fn write_transaction_log(
--
icechunk/src/asset_manager.rs- …
```
> Skip bytes logging in object_store

- Cargo.lock
- icechunk-python/Cargo.toml
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/credentials.py
- icechunk-python/python/icechunk/storage.py
- icechunk-python/src/config.rs
- icechunk-python/src/lib.rs
- icechunk-python/tests/test_credentials.py
`s3_storage` style functions got a new argument:
```
resolve_get_credentials: bool = False
```
If True is passed, pickled repos and sessions will use the result returned the first time `get_credentials` was called, instead of having to run it again.
This speeds up short distributed tasks, since they no longer need to spend time fetching credentials. Tasks will reuse the credentials gathered by the "coordinator"
> Credential refresh can be initialized with the first set of credentials

- Cargo.lock
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/config.rs
- icechunk/Cargo.toml
- icechunk/proptest-regressions/storage/mod.txt
- icechunk/src/storage/mod.rs
- icechunk/src/storage/s3.rs
- icechunk/tests/test_storage.rs
Implements multipart upload for objects (by default) larger than 100MB. All object types are supported.
object_store instances not implemented yet.
> Multipart upload for S3 native Storage instances

- docs/docs/icechunk-python/virtual.md
The parameter name changed at some point from `prefix` to `path`.
> Update local_filesystem_storage parameter in docs

- .github/workflows/python-upstream.yaml
Nightly CI is catching #929 but we don't get notifications
> Fix reporting of failed upstream tests

- icechunk-python/src/repository.rs
- ancestry takes args `branch`, `tag` and `snapshot_id`
- error suggests to use `branch_name` and `tag_name`
- using these as keyword arguments resulted in 
```
Repository.ancestry() got an unexpected keyword argument 'branch_name'
```
> Update value error from ancestry to match interface arguments

- icechunk/src/storage/object_store.rs
Fix GCP anonymous credentials now that object_store `0.12.1` is out
> Correctly support anonymous gcp credentials

- .github/workflows/rust-ci.yaml
- .pre-commit-config.yaml
We can easily run unit tests in macos and all tests in ubuntu arm
> More OSs and architectures in Rust test matrix

- Cargo.lock
- icechunk/Cargo.toml
Recent versions of the official S3 library depend on aws-lc-rs (AWS Libcrypto for Rust). This library is extremely challenging to build in all our wheel environments.
We are downgrading to a March version, right before this change was made.
> Downgrade aws dependencies

- docs/docs/icechunk-python/faq.md
- icechunk-python/python/icechunk/__init__.py
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/lib.rs
- icechunk-python/tests/test_logs.py
- icechunk/src/lib.rs
This introduces a new function `icechunk.set_logs_filter(str)` that allows setting and changing the logs Icechunk will produce.
On module import, we still initialize logs to the value of ICECHUNK_LOG environment variable (or error level if not present).
> Support changing log levels and setting them in Python

- docs/docs/icechunk-python/performance.md
- icechunk-python/python/icechunk/__init__.py
- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/python/icechunk/testing/strategies.py
- icechunk-python/src/config.rs
- icechunk-python/src/errors.rs
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_manifest_splitting.py
- icechunk-python/tests/test_zarr/test_stateful.py
- icechunk/src/ops/manifests.rs
- icechunk/src/ops/mod.rs
- icechunk/src/repository.rs
- icechunk/src/session.rs
Closes #986
Updated docs here: https://icechunk--1002.org.readthedocs.build/en/1002/icechunk-python/performance/#splitting-manifests 
Questions:
1. Should we allow filtering by a prefix?
2. Shall we automatically add the splitting config to the commit's `metadata`? and make sure it's easy to use for creating a new repo?
Decisions:
1. I punted on (1)
2. I've done (2) just to record the config, but didn't add the ability to easily create a ManifestSplittingConfig from the info in metadata.
> Add `rewrite_manifests` EAR-1667

- docs/docs/icechunk-python/faq.md
- icechunk-python/python/icechunk/store.py
- icechunk-python/tests/test_store.py
This new method is not really implementable in Icechunk. If the user created a readonly session there is no real good way to turn it into a writable session, and viceversa.
The implementation we are writing "lies" in this sense. It's pretending to return a new store with the requested readonly-ness, but not really.
> Implement new `with_read_only` Zarr `Store` method

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/config.rs
- icechunk-python/tests/test_config.py
Adds magic methods to the `ManifestPreloadCondition` Python class, so that rather than require users to remember the class method for comparison, then can use the `&` and `|` operators.
```py
icechunk.ManifestPreloadCondition.and_conditions(
[
icechunk.ManifestPreloadCondition.true(),
icechunk.ManifestPreloadCondition.name_matches("foo"),
]
) ==
icechunk.ManifestPreloadCondition.true() & icechunk.ManifestPreloadCondition.name_matches("foo")
```
> Manifest preload magic methods

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/config.rs
- icechunk-python/tests/test_manifest_splitting.py
Builds on #1038 with magic methods for `&` and `|` operators for manifest splitting as well.
```py
ManifestSplitCondition.and_conditions(
[
ManifestSplitCondition.name_matches("temperature"),
ManifestSplitCondition.name_matches("salinity"),
]
) == ManifestSplitCondition.name_matches("temperature") & ManifestSplitCondition.name_matches("salinity")
```
> Manifest splitting magic methods

- icechunk/src/format/manifest.rs
Assuming you don't want redirects from pre-v1.0, this just fixes the URL in the error message.
> Fix URL in error message

- docs/docs/configuration.md
Can't use `1e6` that's a float, not int. Also makes the config blocks executable so we catch these things in the future
> Fix config docs: float -> int

- icechunk/src/ops/mod.rs
This avoids repeating computation (and I/O) when multiple branches/tags repeat parts of the tree (true in almost any repo that has more than one branch/tag)
> Improve performance of GC and stats for repos with multiple refs

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/src/repository.rs
- icechunk/src/asset_manager.rs
- icechunk/src/ops/gc.rs
- icechunk/src/ops/mod.rs
- icechunk/src/ops/stats.rs
- icechunk/src/repository.rs
- icechunk/src/session.rs
- icechunk/tests/test_stats.rs
This adds concurrency to `repo_chunks_storage`.
I verified manually this improves performance very significantly, but benchmarks should be able to tell us.
> Parallelize size statistics gathering

- docs/mkdocs.yml
Uses the mkdocs-redirect plugin we already have installed to manage redirects we need from https://github.com/earth-mover/icechunk/pull/1051
This is part 1 of two PRs to fix all redirect issues (https://github.com/earth-mover/icechunk/issues/1086)
> docs: add redirects to correct for doc reorg

- docs/docs/ingestion/glad-ingest.ipynb
- Currently the notebook within the guide is out of date, still using the old allow_pickling context manager
- Updates the notebook to use the new behaviour described in [the docs](https://icechunk.io/en/stable/parallel/#cooperative-distributed-writes)
- Note to maintainers: I've not run this code, as I don't have access to coiled (nor do I want to incur the cost 👀 ) so you'll need to run this yourselves to get the output before updating the docs!
> Updates the glad-ingest jupyter notebook to reflect the new session fork and session merge capabilities

- .github/ISSUE_TEMPLATE/bug_report.yml
Add pep-723 style metadata to the default issue template. This should render as in: https://github.com/zarr-developers/zarr-python/issues/new?template=bug_report.yml
the hope being that this will guide users to 
1. test their bugs against the dev version of icechunk
2. make sure they are truly reproducible.
3. make bug reports that are very easy to verify
> chore: add pep-723 metadata to default issue template

- icechunk-python/src/errors.rs
- icechunk-python/src/store.rs
- icechunk-python/tests/test_virtual_ref.py
- icechunk/src/format/manifest.rs
- icechunk/src/session.rs
- icechunk/src/store.rs
- icechunk/src/virtual_chunks.rs
- icechunk/tests/test_large_manifests.rs
- icechunk/tests/test_virtual_refs.rs
Now we verify the URL can be parsed as an absolute URL and fail immediately if it cannot.
This will have a small impart on `set_virtual_refs` performance.
> Validate url on set_virtual_ref[s]

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/store.py
Now that virtual chunk containers are mandatory for reads, we should make them at least the default (if not mandatory) for writes.
This gives better UX, users of VZ won't produce repos that are broken for reads, just because they forget to create the containers.
> Make `validate_container` default to True in `set_virtual_ref[s]`

- icechunk-python/tests/test_logs.py
- icechunk/src/asset_manager.rs
We are emiting a warning first time we see a manifest that is more than half the cache size. Same for snapshots that are larger than 1/5 the cache size.
Closes: #1112
> Warn if caches are too small

- icechunk-python/tests/test_can_read_old.py
- icechunk-python/tests/test_concurrency.py
- icechunk-python/tests/test_config.py
- icechunk-python/tests/test_regressions.py
- icechunk-python/tests/test_virtual_ref.py
- icechunk/src/virtual_chunks.rs
- icechunk/tests/test_virtual_refs.rs
This is more secure: Now repository creators cannot create containers with prefixes such as `s3://a` which would match too more than intended.
Example: same for things like bucket like `foo-dev` and `foo-prod`, can no longer be both authorized by a `s3://foo` container.
Existing containers, persisted to config files still work because Icechunk will automatically add the trailing `/` if needed.
Closes: #1125
Closes: #1100
> Force virtual chunk containers ur_prefix to finish in /

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/repository.py
- icechunk-python/src/repository.rs
- icechunk-python/tests/test_inspect.py
- icechunk/src/inspect.rs
- icechunk/src/lib.rs
Example JSON:
```json
{
"id": "BYJMXJ1CHYE86YSHESR0",
"parent_id": "X8NA4KMB3XYEDM2FAJEG",
"flushed_at": "2025-04-15T18:40:41.944920Z",
"commit_message": "write data again with more splits",
"metadata": {},
"manifests": [
{
"id": "19KPV7V2275XRM01YAWG",
"size_bytes": 154,
"num_chunk_refs": 1
},
{
"id": "2PQ1EA39NB2VK7QK688G",
"size_bytes": 151,
"num_chunk_refs": 1
},
{
"id": "7V2NE5Q4H7SN9QF0ZHJ0",
"size_bytes": 153,
"num_chunk_refs": 1
},
{
"id": "7WT30WPG1HF0P2QXGV6G",
"size_bytes": 152,
"num_chunk_refs": 1
},
{
"id": "88Z1G93EH4VF9X28BBHG",
"size_bytes": 154,
"num_chunk_refs": 1
},
{
"id": "B81H9ZEGPV7E15CWXA10",
"size_bytes": 153,
"num_chunk_refs": 1
},
{
"id": "D6QG80A0HJW564ZXRBRG",
"size_bytes": 155,
"num_chunk_refs": 1
},
{
"id": "DDPY0EEPKZXW1ACW41HG",
"size_bytes": 152, …
```
> Add `Repository.inspect_snapshot` to inspect snapshot data in JSON

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/src/config.rs
- icechunk-python/tests/test_config.py
- icechunk/src/asset_manager.rs
- icechunk/src/config.rs
- icechunk/src/repository.rs
- icechunk/src/session.rs
- icechunk/tests/test_gc.rs
- icechunk/tests/test_stats.rs
This PR is in no way final, or perfect. It adds a semaphore to the AssetManager, which will limit concurrency per repo to a certain configurable value (default 256 concurrent requests).
Known ways in which this is not great:
* There is a minor source of extra concurrency: large objects can be further devided in smaller requests by the `Storage` implementation. This is solvable by having the Storage share the same semaphore.
* The semaphore doesn't survive serialization. If the repo is serialized now there are two semaphores and double the max requests. Users should half the permitted max manually.
* Limits are per repo, users having multiple repos open at once will see more requests (this is again solvable by users by lowering the allowed max, but not ideal)
> Introduce an HTTP concurrency limiter per repo

- icechunk-python/tests/test_regressions.py
- icechunk/src/session.rs
This fixes a bug where nodes with names such as `foo.` or `foo)` cannot be retrieved back from the repository.
> fix: special characters in node names

- docs/docs/virtual.md
I just ran the example with fsspec==2025.5.1 and got an error. Providing `anon=True` fixed it for me.
> add anon=True for virtual store example

- .github/workflows/publish-rust-library.yml
- .github/workflows/rust-ci.yaml
- .pre-commit-config.yaml
- Justfile
- docs/docs/contributing.md
Prior to this PR the `just` pre-commit step was very slow (45 seconds or more) which makes it very likely that contributors (and specifically me) will just skip pre-commit checks. In this PR I:
1.  add a new `just` command with only the faster steps for use in pre-commit
2. Filter to only run when the relevant files change (before even changing just the python parts of icechunk-python triggered rust checks)
3. Keep using the old (complete checks) in CI
This does check less, but I think overall it's better because the alternative with the full pre-commit checks is that people (again, me) don't run them at all. Which is worse.
`time pre-commit run --all-files`
**This PR:** `3.76s user 0.89s system 107% cpu 4.325 total`
**main:** `125.57s user 10.14s system 358% cpu 37.851 total`
> Split up just pre-commit to massively speed up pre-commit

- icechunk-python/python/icechunk/_icechunk_python.pyi
- icechunk-python/python/icechunk/session.py
- icechunk-python/src/session.rs
- icechunk-python/tests/test_timetravel.py
- icechunk/src/session.rs
Users can now choose to save their sessions to an anonymous snapshot instead of committing, which updates a branch.
For this they use the `Session.flush` method. `flush` takes the same arguments as `commit` (without the rebase-related arguments), and returns the ID of the newly created snapshot.
The new snapshot is not pointed by any branches or tags.
> Add `Session.flush` to allow anonymous snapshot creation
