earth-mover/icechunk

README.md
Noticed two typos in the docs.
=> Typo fix jbusecke

.mailmap
With such a chance would look like
❯ git shortlog -sn
276  Sebastián Galkin
66  Matthew Iannucci
23  Orestis Herodotou
18  Deepak Cherian
14  Ryan Abernathey
12  Joe Hamman
7  dependabot[bot]
3  Joseph Hamman
2  Aimee Barciauskas
2  Tom Nicholas
whenever without:
❯ git shortlog -sn
166  Sebastian Galkin
110  Sebastián Galkin
66  Matthew Iannucci
23  Orestis Herodotou
18  Deepak Cherian
14  Ryan Abernathey
12  Joe Hamman
7  dependabot[bot]
3  Joseph Hamman
2  Aimee Barciauskas
2  Tom Nicholas
=> Unify both of Sebastiáns in mailmap

.gitattributes
Notebooks are fake lines of code
=> Create .gitattributes to change linguist accounting

README.md
the current link the spec is incorrect
=> correct ref to spec.md

docs/README.md, docs/docs/contributing.md, docs/docs/faq.md, docs/docs/icechunk-rust.md, docs/docs/overview.md, docs/docs/sample-datasets.md, docs/docs/spec.md, docs/docs/stylesheets/homepage.css, docs/mkdocs.yml, docs/poetry.lock, docs/pyproject.toml
* Adds contributors to bottom of pages
* Adds titles to pages
* Fixes mobile overlay on homepage
=> fix(docs): Docs postlaunch fixes

docs/docs/icechunk-python/xarray.md
=> [Docs] add note for requirements of tutorial data download

icechunk/src/format/mod.rs, icechunk/src/storage/object_store.rs, icechunk/src/storage/s3.rs, icechunk/src/storage/virtual_ref.rs
This provides an approach to deal with https://github.com/earth-mover/icechunk/issues/277
=> `ByteRange` can do last n bytes now

icechunk-python/pyproject.toml, icechunk-python/tests/test_zarr/test_api.py
Let's see if CI passes. If not, we'll do some work next week to bring things into alignment.
=> update zarr pin to v3.0.0b1

Cargo.lock, icechunk-python/Cargo.toml, icechunk-python/src/lib.rs, icechunk-python/src/streams.rs
=> [chore] Switch pyo3 async out for pyo3 async runtimes

.github/workflows/python-check.yaml, Justfile, icechunk-python/src/lib.rs
I am not sure how this slipped through..
=> Fix python lint action

docs/docs/sample-datasets.md
Just noticed that the example of NOAA data did not work.
=> Fix example NOAA dataset

docs/docs/overview.md
=> Fix broken link

icechunk-python/tests/test_regressions.py, icechunk/src/format/manifest.rs
=> fix: chunks from different arrays are mixed during commit

Cargo.lock, Changelog.python.md, Changelog.rust.md, icechunk-python/Cargo.toml, icechunk-python/pyproject.toml, icechunk/Cargo.toml
=> Update changelogs, bump version numbers

.github/workflows/python-check.yaml, icechunk-python/pyproject.toml, icechunk-python/tests/test_regressions.py
1. Remove one reinstall
2. Use pytest-xdist
=> Speedup python CI

icechunk-python/python/icechunk/__init__.py, icechunk-python/tests/test_timetravel.py
=> Set store to writeable after creating a branch

icechunk-python/tests/test_virtual_ref.py, icechunk/tests/test_virtual_refs.rs
Use our own anonymous data for virtual ref anonymous test
Closes #462
=> Temporarily fix virtual tests

icechunk-python/tests/test_zarr/test_stateful.py
Needs https://github.com/zarr-developers/zarr-python/pull/2531 merged and released, but it passes locally!
=> Wire up Zarr stateful tests

icechunk/src/storage/object_store.rs
=> Canonicalize local fs object store

icechunk-python/pyproject.toml, icechunk-python/tests/test_can_read_old.py, icechunk-python/tests/test_zarr/test_stateful.py, icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py, icechunk/src/change_set.rs, icechunk/src/session.rs, icechunk/src/store.rs
=> Re-implement `list_dir`

icechunk/src/storage/mod.rs
Its not automatic like aws because it doesnt use an actual google cloud client, it builds its own
=> Fix FromEnv for gcs storage

icechunk/src/asset_manager.rs, icechunk/src/storage/logging.rs
=> Add tests to check no double asset download

icechunk-python/src/config.rs, icechunk-python/src/repository.rs, icechunk-python/tests/test_config.py
This makes it far easier to configure repositories from Python
Closes: #559
=> Mutable python config

.github/workflows/rust-ci.yaml
I see errors because this container is not created every once in a while.
Let's try this, not very confident it will work.
=> More time for docker to initialize

icechunk-python/python/icechunk/__init__.py
=> Fix error on: from icechunk import *

Cargo.lock, Changelog.python.md, icechunk-python/Cargo.toml, icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/src/config.rs, icechunk-python/tests/test_config.py, icechunk/Cargo.toml
Also add constructor to `RepositoryConfig`
=> Release 0.1.0-alpha.15

docs/docs/sample-datasets.md, icechunk-python/notebooks/demo-dummy-data.ipynb, icechunk-python/notebooks/demo-s3.ipynb, icechunk-python/notebooks/memorystore.ipynb, icechunk-python/notebooks/performance/era5_xarray-Icechunk.ipynb, icechunk-python/notebooks/version-control.ipynb
=> Update some notebooks to latest syntax

icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py, icechunk/src/session.rs
=> Fix bug in manifest splitting

Cargo.lock, icechunk-python/Cargo.toml, icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/python/icechunk/repository.py, icechunk-python/python/icechunk/session.py, icechunk-python/src/repository.rs, icechunk-python/src/session.rs, icechunk-python/src/store.rs, icechunk-python/src/streams.rs, icechunk-python/tests/test_commit_properties.py, icechunk-python/tests/test_timetravel.py, icechunk/src/asset_manager.rs, icechunk/src/ops/gc.rs, icechunk/src/repository.rs, icechunk/src/session.rs, icechunk/tests/test_gc.rs
This allows to do more efficient ancenstry from python in an async context. Also pagination is enabled because we return an AsyncIterator and we take snapshot ids.
=> Implement Python's Repository.async_ancestry

icechunk-python/tests/run_xarray_backends_tests.py, icechunk-python/tests/test_distributed_writers.py, icechunk-python/tests/test_zarr/test_array.py, icechunk-python/tests/test_zarr/test_store/test_icechunk_store.py
Woops, I don't understand how these weren't failing on the PR branch :( Sorry!
=> Fix pickling tests

icechunk/src/repository.rs, icechunk/src/storage/logging.rs, icechunk/src/storage/mod.rs, icechunk/src/storage/object_store.rs, icechunk/src/storage/s3.rs
This of course suffers from race conditions, it's just a quick check.
=> Don't create a repository unless its prefix is empty

README.md, docs/docs/icechunk-python/quickstart.md
=> Add conda-forge badge & installation instructions for conda

icechunk/src/refs.rs, icechunk/src/repository.rs, icechunk/src/storage/logging.rs, icechunk/src/storage/mod.rs, icechunk/src/storage/object_store.rs, icechunk/src/storage/s3.rs, icechunk/tests/test_storage.rs
Some conditions weren't really errors, but expected results. Changing those cases richer result types.
=> Better `Storage` errors

icechunk/src/asset_manager.rs, icechunk/src/session.rs
- rebase
- commit
- storage reads/writes
=> Add logging to complex operations

icechunk/src/store.rs
We were pulling the chunk bytes before responding. Now we don't hit object store.
Closes #698
=> Faster `exists` method in the Store

Cargo.lock, icechunk/Cargo.toml, icechunk/src/repository.rs
Apparently the author of serde_yml is not a good actor:
https://nitter.poast.org/davidtolnay/status/1883906113428676938
Closes: #703
=> Change yml dependency

icechunk-python/tests/test_stateful_repo_ops.py, icechunk-python/tests/test_store.py, icechunk/src/store.rs
=> Don't write `dimension_names` to JSON if null

icechunk-python/src/repository.rs, icechunk-python/tests/test_timetravel.py, icechunk/src/format/transaction_log.rs, icechunk/src/session.rs
Now the coordinates for all modified chunks are included
=> `diff` and `status` return richer information

docs/docs/icechunk-python/dask.md, docs/docs/icechunk-python/xarray.md
- Added imports where necessary
- kept track of snapshot ids
- fixed typoes
=> Update xarray and zarr docs

docs/docs/icechunk-python/cheatsheets/git-users.md, docs/docs/icechunk-python/version-control.md, icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/python/icechunk/repository.py, icechunk-python/src/repository.rs, icechunk-python/src/streams.rs, icechunk-python/tests/test_commit_properties.py
=> Python's `Repository.ancestry` now returns an iterator

icechunk/tests/test_storage.rs
For when gcs is eventually tested formally
=> Fix for storage test 

icechunk/src/storage/s3.rs
=> Only write content-type if the object store accepts metadata

docs/docs/icechunk-python/storage.md
=> [Docs] Remove note about s3 express zone

icechunk-python/python/icechunk/session.py, icechunk-python/tests/test_dask.py
=> Support nested `allow_pickling` contexts

design-docs/009-tigris-support.md, icechunk/src/storage/s3.rs
Closes #793
I confirmed that this works
1. by deleting my default region in `.aws/config`.
2. Creating a new repo on tigris. This action fails without this change.
=> Set fallback region

icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/src/repository.rs, icechunk-python/tests/test_gc.py, icechunk/src/ops/gc.rs, icechunk/src/storage/logging.rs, icechunk/src/storage/mod.rs, icechunk/src/storage/object_store.rs, icechunk/src/storage/s3.rs, icechunk/tests/test_gc.rs
=> Garbage collection results expose number of bytes deleted

docs/docs/icechunk-python/storage.md
=> docs: Fix rendering of tab

icechunk/src/storage/object_store.rs
I was curious about your general implementation from #723, and two things I thought could be better (at least provide simpler maintenance, although probably not better performance)
- `mk_object_store` is never async, and so the method doesn't have to be async and the trait doesn't have to be async-capable
That said, no strong feelings if you don't want to merge this.
Nothing immediately came to mind about why the object_store backend could be slower, other than if you're unintentionally re-creating the store multiple times. (I will say that storing a `OnceCell` reference in the store config "looks" weird to me, but maybe just because I haven't needed to use that pattern before)
=> Minor object-store backend cleanup

icechunk-python/benchmarks/README.md, icechunk-python/benchmarks/conftest.py, icechunk-python/benchmarks/datasets.py, icechunk-python/benchmarks/helpers.py, icechunk-python/benchmarks/most_recent.sh, icechunk-python/benchmarks/runner.py, icechunk-python/benchmarks/tasks.py, icechunk-python/benchmarks/test_benchmark_writes.py
🫣 Not my best work but....
```
python benchmarks/runner.py --skip-setup --pytest '-k test_write_simple' --where 's3|s3_ob|gcs' main
```
```
-------- benchmark 'test_write_simple_1d simple-1d': 3 tests --------
Name (time in s)                                     Median
---------------------------------------------------------------------
test_write_simple_1d[simple-1d] (g/gcs_main_95e)     5.2314 (3.15)
test_write_simple_1d[simple-1d] (g/s3_main_95ef)     1.6622 (1.0)
test_write_simple_1d[simple-1d] (g/s3_ob_main_9)     1.6909 (1.02)
---------------------------------------------------------------------
```
=> Benchmarks for writes

docs/docs/icechunk-python/expiration.md, docs/docs/icechunk-python/index.md, docs/docs/icechunk-python/version-control.md, docs/mkdocs.yml, icechunk-python/notebooks/expiration.ipynb, icechunk-python/notebooks/version-control.ipynb, icechunk-python/python/icechunk/dask.py
Rendered view: https://icechunk--857.org.readthedocs.build/en/857/icechunk-python/expiration/
=> Add expiration/GC notebook

icechunk-python/tests/test_stateful_repo_ops.py
Looks like we forgot to uncomment once the bugs were fixed.
=> Uncomment `delete_branch` in stateful repo ops test

icechunk-python/tests/test_stateful_repo_ops.py, icechunk/src/repository.rs
=> Disallow tag/branch creation with non-existing snapshot

icechunk/src/storage/mod.rs
=> Fail when creating Storage for Tigris using s3_compatible

docs/docs/icechunk-python/configuration.md
Addresses the user confusion about chunk caching in https://github.com/earth-mover/icechunk/discussions/898
=> Update configuration.md to clarify caching

docs/docs/icechunk-python/configuration.md, icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/src/config.rs, icechunk-python/tests/test_config.py, icechunk/src/storage/mod.rs, icechunk/src/storage/s3.rs, icechunk/tests/common/mod.rs, icechunk/tests/test_storage.rs
Object store based Storage instances are not supported yet, object_store doesn't have a way to set the Storage Class.
Closes: #871
=> S3 Storage supports setting storage class

.github/workflows/python-upstream.yaml
(again)
Confirmed this works now, we should get issues like #944, #945 if a nightly test fails
=> Fix upstream failure reporting

icechunk-python/examples/high_concurrency.py
* GCS
* not killing the cluster
* coiled workspaces
* different chunk sizes
=> High concurrency script learns new tricks

docs/docs/overview.md
Fixes a typo identified in #998.
=> Fix spelling typo

icechunk-python/tests/test_timetravel.py, icechunk/src/format/mod.rs, icechunk/src/format/snapshot.rs, icechunk/src/session.rs
Closes #708 
* Should this be exposed to python somehwere?
=> Add initial commit id as constant

docs/docs/faq.md, docs/docs/overview.md, docs/docs/spec.md
Also addresses backwards compatibility.
=> Cleanup outdated warnings and fix spec doc

icechunk-python/python/icechunk/_icechunk_python.pyi
I have checked this does the right thing
=> Fix enum docstring

icechunk-python/tests/test_zarr/test_properties.py, icechunk-python/tests/test_zarr/test_stateful.py
Should merge after the next zarr release
=> Compat with latest zarr strategies

icechunk/src/session.rs
=> Better error message on clock drift.

icechunk/src/storage/s3.rs
=> Some object stores (Ceph) don't like double quotes in etags

docs/docs/faq.md, icechunk-python/tests/test_store.py, icechunk-python/tests/test_zarr/test_properties.py, icechunk/src/session.rs
=> Fix ranged reads of inline chunks.

icechunk/src/config.rs
Nodes: 10k -> 30k
Chunk refs: 5M -> 15M
Closes: #1124
=> Larger default caches

icechunk-python/src/repository.rs
=> Fix: ManifestFileInfo properties

.github/workflows/python-upstream.yaml, icechunk-python/python/icechunk/xarray.py
need to open this to test this out by inducing a failure
=> CI: update existing mypy nightly issue instead of making a new one

icechunk-python/python/icechunk/xarray.py
closes: https://github.com/earth-mover/icechunk/issues/1262
=> Fix (ignore) mypy errors generated from supporting divergent xarray imports

icechunk/src/config.rs
=> Increase snapshot cache size

icechunk-python/tests/run_xarray_backends_tests.py
fix remaining xarray backend test errors.
=> update test machinery to support multiple saves with dask

icechunk-python/python/icechunk/_icechunk_python.pyi, icechunk-python/python/icechunk/credentials.py, icechunk-python/src/config.rs
=> Support anonymous GCS in python
